### ISSUE TITLE
Also supports BLE devices from the Magic Lantern app

### ISSUE THREAD

**Issue by julianjwong** [8none1/elk-bledob#1]
Thanks for all your awesome work on custom BLE LED integrations. I found that this Elk BLE Dob integration also supports devices that are used via the Magic Lantern app.

**Comment by 8none1** [comment]
Thanks for the info.   

Can you tell me how your devices identify themselves, what is a typical device name?

**Comment by julianjwong** [comment]
So unfortunately I haven't been able to get the devices added to HA yet but here's what I can share about the devices:

Name in Lotus for my two LED corner light bars/tubes (addressable RGB)
MELK-OA10 10
MELK-OA10 25
Type is described as 
3-RGB Magic Strip/Light


From the Magic Lantern app I can see the Mac Address 
BE:FF:A5:00:14:10
BE:FF:E5:00:07:25


I've tried adding directly via HA and the Elk integration as they aren't auto detected but no luck.

I thought it could be a range issue so I've put an Esp32 Bluetooth Proxy in the same room but still no go. I'm pretty sure the proxy is working as I'm able to control some iDeal addressable RGB led strip lights with your other integration. I'll try moving the Elk lights closer to my HA server a bit later
![Screenshot_20240430_170513_LotusLamp X](https://github.com/8none1/elk-bledob/assets/32351689/d27e301a-0272-434b-a57d-35f0acccbcf9)

**Comment by 8none1** [comment]
It sounds like the devices aren't actually supported by this integration.  But, I think you should check out this one instead:  https://github.com/dave-code-ruiz/elkbledom

It does support devices named `MELK`, because I use it myself :)

**Comment by julianjwong** [comment]
Thanks for sharing the link! Worked for me!
Still need to work out if my Tuya Bluetooth battery lights have a compatible 3rd party integration without needing a BT Tuya mesh hub. And also my Bliss lights galaxy projector.

**Comment by 8none1** [comment]
If you're interested in trying to reverse engineer the BT commands I recommend this device:

https://www.nordicsemi.com/Products/Development-tools/nRF-Sniffer-for-Bluetooth-LE

It can be bought pretty cheaply (less than £10) and has Wireshark plugins which make decoding the protocol pretty easy.

My experience of Tuya BT mesh is that it's a lot easier to just buy a Tuya hub and use the existing Tuya integration to control the devices.  There is an integration out there which has reversed engineered the BT mesh protocol but it's a lot of effort and the Tuya integration is very good.
